django/example/example/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('task/', include("task.urls")),
]

django/example/hello/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("brian", views.brian, name="brian"),
    path("<str:name>", views.greetpage, name="greet"),
]

django/example/newyear/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index")
]

django/example/task/urls.py
from django.urls import path

from . import views

app_name = 'task'
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add"),
    path("adddjango", views.adddjango, name="adddjango"),
]

django/example/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def brian(request):
    return HttpResponse("Hello, Brian!")

def greet(request, name):
    return HttpResponse(f"Hello, {name.capitalize()}!")

def greetpage(request, name):
    return render(
        request,
        "hello/greet.html",
        {
            "name": name.capitalize()
        }
    )

django/example/newyear/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(
        request, "newyear/index.html",
        {
            "newyear": now.month == 1 and now.day == 1
        }
    )

django/example/task/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse

# tasks = ["foo", "bar", "baz"]

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    priority = forms.IntegerField(label="Priority", min_value=1, max_value=10)

# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []

    return render(
        request, "task/index.html",
        {
            "tasks": request.session["tasks"] 
        }
    )

def add(request):
    return render(request, "task/add.html")

def adddjango(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("task:index"))
        else:
            return render(
                request,
                "task/adddjango.html",
                {
                    "form": form
                }
            )

    return render(
        request, "task/adddjango.html",
        {
            "form": NewTaskForm()
        }
    )

django/example/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello!</title>
    </head>
    <body>
        <h1>Hello, {{ name }}!</h1>
    </body>
</html>

django/example/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello!</title>
    </head>
    <body>
        <h1>Hello, world!</h1>
    </body>
</html>

django/example/task/templates/task/add.html
{% extends "task/layout.html" %}

{% block body %}
<h1>Add Task:</h1>
<form>
    <input type="text" name="task">
    <input type="submit">
</form>
<a href="{% url 'task:index' %}">Return to Tasks</a>
{% endblock %}

django/example/task/templates/task/adddjango.html
{% extends "task/layout.html" %}

{% block body %}
<h1>Add Task with Django:</h1>
<form accept="{% url 'task:add' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>
<a href="{% url 'task:index' %}">Return to Tasks</a>
{% endblock %}

django/example/task/templates/task/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tasks</title>
    </head>
    <body>
        <h1>Tasks:</h1>
        <ul>
            {% for task in tasks %}
                <li>{{ task }}</li>
            {% empty %}
                <li>No tasks.</li>
            {% endfor %}
        </ul>
        <a href="{% url 'task:adddjango' %}">Add a New Task</a>
    </body>
</html>

django/example/task/templates/task/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tasks</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>